import {BANK_VERSION,EVIDENCE_DATE,SKILLS,REFERENCES,buildQuestionBank} from './assessment-data.js';
import {MODES,MODEL,ensureLab,assessmentReportSummary,isPractice,shuffled,validAnswer,correctAnswer,misconception,learnerProfile,createAttempt,saveResponse,reviewPractice,continuePractice,finishAttempt,answerText} from './assessment-core.js';
import {AssessmentMedia} from './assessment-media.js';
import {lessonDiagram,MECHANISMS} from './assessment-diagrams.js';
import {TrainingFootage,footageForQuestion} from './training-footage.js';
import {presentQuestion,recordExposure,practiceAvailable,attemptName} from './assessment-evidence.js';
import {VISUAL_VERSION} from './assessment-visuals.js';
import {learningSnapshot} from './learning-profile.js';
import {insightMarkup} from './learning-insights.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const skillFor=q=>SKILLS.find(s=>s.id===q.skill);
const TYPES={single:'单项判断',multi:'多项选择',order:'步骤排序',hotspot:'图像定位'};
const refLinks=ids=>[...new Set(ids)].map(id=>`<a href="${REFERENCES[id].url}" target="_blank" rel="noopener noreferrer">${esc(REFERENCES[id].title)} <span>↗</span></a>`).join('');
const modeCards=[['pre','01','先测起点','16 题，覆盖八个能力领域，保留首次结果。'],['post','02','独立综合检测','16 题保留检测；题目已曝光时按同卷复习记录。'],['adaptive','✦','AI 定向复练','根据每次作答调整后续练习，图文微课随错因展开。'],['retry','04','迁移复测','只使用未见保留题，最多 8 题；题池用尽后转入复练。']];
export class AssessmentLab{
 constructor(root,api){this.root=root;this.api=api;this.bank=null;this.view='hub';this.attempt=null;this.index=0;this.media=null;this.operation=0;this.uiAbort=null;}
 get session(){return this.api.getSession();}
 get active(){return !!(this.attempt&&!this.attempt.submitted&&!this.attempt.abandoned&&this.view==='question');}
 async load(){if(this.bank)return;this.loading ||= Promise.all(['./assessment-cases.json','./or-field/script.json'].map(async url=>{const r=await fetch(url);if(!r.ok)throw new Error('题库资料加载失败');return r.json();})).then(([cases,field])=>{this.cases=cases.cases;this.bank=buildQuestionBank(cases,field);}).catch(error=>{this.loading=null;throw error;});await this.loading;}
 async mount(){
  const op=++this.operation;this.releaseMedia();this.root.classList.add('assessment-lab');
  this.root.innerHTML='<div class="al-loading" role="status"><span>✦</span><h1>正在打开独立检测</h1><p>加载题库与本机学习记录</p></div>';
  try{await this.load();if(op!==this.operation)return;this.view='hub';this.attempt=null;this.renderHub();}catch(error){if(op!==this.operation)return;this.root.innerHTML=`<div class="al-loading"><h1>检测资料暂未打开</h1><p>${esc(error.message)}</p><button class="primary" data-action="reload">重新加载</button></div>`;this.bind();}
 }
 unmount(){++this.operation;this.releaseMedia();this.root.classList.remove('assessment-lab');if(this.onClick)this.root.removeEventListener('click',this.onClick);}
 releaseMedia(){this.media?.destroy();this.media=null;this.footage?.destroy();this.footage=null;}
 log(type,data={}){this.api.log('intelligent_'+type,{bankVersion:BANK_VERSION,imageVersion:VISUAL_VERSION,...data});this.api.save();}
 frame(content){this.releaseMedia();this.root.classList.add('assessment-lab');this.root.innerHTML=content;this.bind();}
 bind(){
  if(this.onClick)this.root.removeEventListener('click',this.onClick);
  this.onClick=e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;this.action(b.dataset.action,b.dataset).catch(error=>this.notice(error.message));};
  this.root.addEventListener('click',this.onClick);
 }
 async action(action,d){
  if(action==='reload')return this.mount();
  if(action==='knowledge')return this.api.openKnowledge?.(d.node||null);
  if(action==='start')return this.start(d.kind,{focus:d.skill||null,caseId:d.case||null});
  if(action==='resume')return this.resume(d.id);
  if(action==='hub'){this.attempt=null;this.view='hub';this.api.lock(false);return this.renderHub();}
  if(action==='section')return this.root.querySelector('#'+d.section)?.scrollIntoView({behavior:'smooth',block:'start'});
  if(action==='lesson')return this.renderLesson(d.skill);
  if(action==='result'){this.attempt=ensureLab(this.session).attempts.find(a=>a.id===d.id);this.view='result';return this.renderResult();}
  if(action==='pathway'){
   const m=MECHANISMS[d.id];if(!m)return;this.root.querySelectorAll('[data-pathway-node]').forEach(n=>n.classList.toggle('blocked',n.dataset.pathwayNode===m.block));this.root.querySelectorAll('[data-action="pathway"]').forEach(n=>n.setAttribute('aria-pressed',String(n.dataset.id===d.id)));this.root.querySelector('.al-pathway-note').textContent=m.text;this.log('mechanism_view',{mechanism:d.id,learningOnly:true});return;
  }
  if(action==='export')return this.exportReport();
  if(action==='print')return window.print();
  if(action==='review-question'){this.reviewIndex=+d.index;return this.renderReview();}
  if(action==='result-back')return this.renderResult();
  if(action==='answer'){this.choose(d.id);return;}
  if(action==='confidence'){this.confidence=d.id;this.updateDraft();return this.updateInputs();}
  if(action==='uncertain'){this.choice='uncertain';this.updateDraft();this.media?.setPick(null);return this.updateInputs();}
  if(action==='order'){const order=Array.isArray(this.choice)?[...this.choice]:shuffled(this.q.options.map(o=>o.id),this.attempt.seed+this.index),i=order.indexOf(d.id),j=i+(d.direction==='up'?-1:1);if(j>=0&&j<order.length)[order[i],order[j]]=[order[j],order[i]];this.choice=order;this.updateDraft();return this.renderOptions();}
  if(action==='hint')return this.showHint();
  if(action==='confirm')return this.confirm();
  if(action==='page'){this.index=+d.index;return this.renderQuestion();}
  if(action==='submit')return this.finish();
  if(action==='next-practice'){
   if(this.index<this.attempt.questionIds.length-1){this.index++;return this.renderQuestion();}
   if(continuePractice(this.session,this.attempt,this.bank)){this.index++;this.api.save();return this.renderQuestion();}
   return this.finish();
  }
  if(action==='pause'){this.api.lock(false);this.log('pause',{attempt:this.attempt.id,answered:Object.keys(this.attempt.responses).length});this.attempt=null;this.view='hub';return this.renderHub();}
 }
 notice(message){const box=this.root.querySelector('.al-notice');if(box){box.textContent=message;box.hidden=false;}else this.api.toast(message);}
 async start(kind,opts={}){
  const op=this.operation;await this.load();if(this.active||op!==this.operation)return;
  const pending=ensureLab(this.session).attempts.find(a=>!a.submitted&&!a.abandoned&&a.bankVersion===BANK_VERSION&&(a.sourceKind||a.kind)===kind&&(a.focus||null)===(opts.focus||null)&&(a.caseId||null)===(opts.caseId||null));if(pending)return this.resume(pending.id);
  this.attempt=createAttempt(this.session,kind,this.bank,opts);this.index=0;this.view='question';this.api.lock(true);
  this.log('start',{attempt:this.attempt.id,kind,questionIds:this.attempt.questionIds,assistance:isPractice(this.attempt)});this.renderQuestion();
 }
 resume(id){const a=ensureLab(this.session).attempts.find(a=>a.id===id);if(!a||a.submitted||a.abandoned||a.bankVersion!==BANK_VERSION)return;
  this.attempt=a;this.index=Math.max(0,a.questionIds.findIndex(id=>!a.responses[id]||isPractice(a)&&!a.reviewed.includes(id)));if(a.questionIds.every(id=>a.responses[id]))this.index=a.questionIds.length-1;this.view='question';this.api.lock(true);this.log('resume',{attempt:a.id});this.renderQuestion();}
 renderHub(){
  this.view='hub';const lab=ensureLab(this.session),profile=learnerProfile(this.session,this.bank),done=lab.attempts.filter(a=>a.submitted&&a.bankVersion===BANK_VERSION),open=lab.attempts.filter(a=>!a.submitted&&!a.abandoned&&a.bankVersion===BANK_VERSION),weak=[...profile].sort((a,b)=>b.priority-a.priority).slice(0,3),hasEvidence=profile.some(s=>s.independent||s.trainingSignals);
  this.frame(`<div class="al-hub">
   <header class="al-hero"><div><p class="al-kicker">INDEPENDENT ASSESSMENT · 独立检测</p><h1>看清每一次判断，<br>练到真正会辨认。</h1><p class="al-intro">真实影像里的观察，具体情境中的选择。<br>AI 学习教练根据你的作答，为下一步练习找到方向。</p><div class="al-hero-stats"><span><b>${this.bank.length}</b> 图文题</span><span><b>8</b> 能力领域</span><span><b>15</b> 真实病例</span></div></div><div class="al-hero-art"><figure><img src="./real-cases/CT-004/preview-unmarked.webp" alt="真实胸部 CT" width="340" height="230"><figcaption>真实 CT · 连续阅片</figcaption></figure><figure><img src="./or-field/clean/frames/s02_y_clear.jpg" alt="真实肺门分离术野" width="340" height="230"><figcaption>真实术野 · 观察与定位</figcaption></figure><div class="al-art-label"><span>✦</span><div><strong>观察 → 判断 → 找错因 → 换题验证</strong><small>你的记录决定复练重点</small></div></div></div></header>
   <section id="al-footage" class="al-footage-section"><div class="al-section-heading"><div><p class="al-mini">WATCH & LEARN</p><h2>先看真实手术，再练习判断</h2></div><p>4 段录像 · 15 张关键帧 · 本页直接播放</p></div><div class="al-training-footage"></div></section>
   <nav class="al-local-nav" aria-label="检测中心"><button data-action="section" data-section="al-footage">手术视频</button><button data-action="section" data-section="al-start">开始检测</button><button data-action="section" data-section="al-multidimensional">多维画像</button><button class="li-nav-knowledge" data-action="knowledge">知识图谱 ↗</button><button data-action="section" data-section="al-lessons">图文微课</button><button data-action="section" data-section="al-cases">病例挑战</button><span>依据更新 · ${EVIDENCE_DATE}</span></nav>
   ${open.length?`<div class="al-resume"><div><strong>还有 ${open.length} 次检测可以继续</strong><p>已保存题目和选择，未提交的独立检测不生成成绩。</p></div>${open.slice().reverse().map(a=>`<button class="al-button" data-action="resume" data-id="${a.id}">继续${attemptName(a)} · ${Object.keys(a.responses).length}/${a.maxQuestions} · ${new Date(a.started).toLocaleString('zh-CN',{hour12:false})} · ${esc(a.id.slice(-6))}</button>`).join('')}</div>`:''}
   <section id="al-start" class="al-section"><div class="al-section-heading"><div><p class="al-mini">01 / ASSESS</p><h2>从你的起点开始</h2></div><p>单选 · 多选 · 排序 · CT 阅片 · 术野定位</p></div><div class="al-modes">${modeCards.map(([kind,num,title,text])=>`<article class="al-mode ${kind==='adaptive'?'al-featured':''}"><span class="al-mode-number">${num}</span><h3>${title}</h3><p>${text}</p><div class="al-mode-meta"><span>${kind==='retry'?'最多 8':MODES[kind].count} 题</span><span>${kind==='adaptive'?'逐题反馈':'提交后解析'}</span></div><button class="al-button ${kind==='adaptive'?'al-primary':''}" data-action="start" data-kind="${kind}">${kind==='adaptive'?'生成我的复练':'开始检测'} <span>↗</span></button></article>`).join('')}</div></section>
   ${insightMarkup(learningSnapshot(this.session,this.bank),{id:'al-multidimensional'})}
   <section id="al-profile" class="al-section"><div class="al-section-heading"><div><p class="al-mini">02 / UNDERSTAND</p><h2>复练计划与证据明细</h2></div><p>首次未见题、同题订正与提示使用分别记录</p></div><div class="al-insight-grid"><article class="al-skill-panel">${this.profileMarkup(profile)}</article><aside class="al-coach"><span class="al-ai-icon">✦</span><p class="al-mini">AI 学习教练</p><h3>${hasEvidence?'下一步，把精力放在这里':'先完成检测，再了解你的薄弱点'}</h3><p>${hasEvidence?'推荐来自本机真实作答。点击一个领域，可先看微课，也可直接开始定向练习。':'目前没有独立测评证据，不预先给你贴标签。起点检测会同时观察判断和信心。'}</p>${hasEvidence?weak.map((s,i)=>`<button class="al-coach-pick" data-action="start" data-kind="adaptive" data-skill="${s.id}"><span>0${i+1}</span><div><strong>${s.name}</strong><small>${esc(s.errors.at(-1)?.tag||(s.trainingSignals?'六检查点中存在待独立验证的学习记录':s.independent?'换题巩固当前判断':'补充独立作答证据'))}</small></div><b>→</b></button>`).join(''):'<button class="al-button al-primary" data-action="start" data-kind="pre">开始起点检测 →</button>'}<details class="al-model-note"><summary>教练如何判断</summary><p>采用${MODEL.name}与错因匹配，综合已提交答案、信心和提示使用。高信心错误优先纠正；提示后完成单独记录；答题速度不作为能力结论。</p><p>掌握估计是练习排序工具，参数尚未经过本课程学生数据校准。仅已记录为未曝光且无提示的检测进入独立画像；旧记录保留成绩，未追踪的曝光不作未见题证明。没有调用云端大模型，记录留在本机。</p></details></aside></div></section>
   <section id="al-lessons" class="al-section"><div class="al-section-heading"><div><p class="al-mini">03 / LEARN</p><h2>一张微课，解决一个理解缺口</h2></div><p>先看观察方法，再换题验证</p></div><div class="al-lesson-grid">${SKILLS.map((s,i)=>`<button class="al-lesson-card" data-action="lesson" data-skill="${s.id}"><span style="--skill-color:${s.color}">0${i+1}</span><h3>${s.name}</h3><p>${s.goal}</p><b>打开图文微课 ↗</b></button>`).join('')}</div></section>
   <section id="al-cases" class="al-section"><div class="al-section-heading"><div><p class="al-mini">04 / TRANSFER</p><h2>把判断放回真实病例</h2></div><p>三方向 · 连续层面 · 缩放与平移</p></div><div class="al-case-grid">${this.cases.map((c,i)=>`<button class="al-case-card" data-action="start" data-kind="case" data-case="${c.id}"><img src="./real-cases/${c.id}/preview-unmarked.webp" alt="${c.id} 真实 CT 预览" loading="lazy" width="250" height="180"><span><strong>${c.id}</strong><small>${['轴位起点','冠状位起点','矢状位起点'][i%3]}</small></span></button>`).join('')}</div></section>
   ${done.length?`<section class="al-section"><div class="al-section-heading"><h2>已完成的检测</h2><p>首次记录保留，不被复练覆盖</p></div><div class="al-history">${done.slice().reverse().map(a=>`<button data-action="result" data-id="${a.id}"><span>${attemptName(a)}<small>${new Date(a.submitted).toLocaleString('zh-CN',{hour12:false})}</small></span><strong>${a.result.score}<small>分</small></strong><span>查看画像与解析 →</span></button>`).join('')}</div></section>`:''}
   <details class="al-evidence"><summary>题目依据与评价说明 <span>2026 分期指南 · 2025 功能评估指南 · 权威解剖教程</span></summary><div class="al-reference-grid">${Object.values(REFERENCES).map(r=>`<article><small>${r.year}</small><a href="${r.url}" target="_blank" rel="noopener noreferrer">${esc(r.title)} ↗</a><p>${esc(r.note)}</p></article>`).join('')}</div><p>题干、情境和解析为本站教学改编。新检测按题等权，多选须完全匹配、排序须完整正确；提示使用不改变作答正误，但单列为辅助完成。前后测按同一蓝图设计，尚未验证等难度。成绩用于本课学习反馈，不代表独立手术资质。真实阅片与虚构情境明确区分。</p><p>题库 ${BANK_VERSION} · 历史旧版成绩独立保留${this.session.kind==='demo'?' · 当前为教师演示记录':''}</p></details>
  </div>`);
  this.footage=new TrainingFootage(this.root.querySelector('.al-training-footage'),{onLearn:data=>this.log('footage_view',data)});
 }
 profileMarkup(profile){return `<div class="al-profile-heading"><h3>八维学习记录</h3><span>掌握估计</span></div>${profile.map(s=>`<div class="al-skill-row"><div><strong>${s.name}</strong><small>${s.independent?`${s.correct}/${s.independent} 道首次未见题无提示答对`:s.trainingSignals?'已有训练线索，尚待独立检测':`暂无可确认的独立证据；无提示订正 ${s.corrections} 次`}</small></div><div class="al-skill-bar" role="meter" aria-label="${s.name}掌握估计" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${s.independent?s.estimate:0}" aria-valuetext="${s.independent?s.estimate+'，'+s.status:'尚未检测'}"><span style="width:${s.independent?s.estimate:0}%;--skill-color:${s.color}"></span></div><span class="al-skill-state ${s.highConfidenceErrors?'al-high-error':''}">${s.status}</span></div>`).join('')}`;}
 renderQuestion(){
  const a=this.attempt,q=this.bank.find(q=>q.id===a.questionIds[this.index]);if(!q)throw new Error('题目不存在');
  presentQuestion(this.session,a,q);this.api.save();
  const r=a.drafts?.[q.id]||a.responses[q.id];this.q=q;this.choice=r?.value??(q.type==='order'?shuffled(q.options.map(o=>o.id),a.seed+this.index):q.type==='multi'?[]:null);this.confidence=r?.confidence||null;this.hints=r?.hints||0;this.elapsedPrior=r?.elapsedMs||0;this.started=performance.now();this.mediaReady=false;
  if(isPractice(a)&&a.reviewed.includes(q.id))return this.renderPracticeFeedback();
  const count=Object.keys(a.responses).length,practiceFootage=isPractice(a)&&footageForQuestion(q);
  this.frame(`<div class="al-exam"><header class="al-exam-top"><div><p class="al-mini">${isPractice(a)?'PRACTICE · 可用提示':a.kind==='diagnostic'?'DIAGNOSTIC · 逐知识点判断':'INDEPENDENT · 独立作答'}</p><h1>${attemptName(a)}</h1></div><div class="al-exam-progress"><span>第 ${this.index+1} / ${a.maxQuestions} 题</span><progress value="${count}" max="${a.maxQuestions}" aria-label="已保存题数"></progress><small>已保存 ${count} 题</small></div><button class="al-button" data-action="pause">保存并稍后继续</button></header>
   <div class="al-exam-guard">${a.kind==='retry'?`本组 ${a.questionIds.length} 道未见保留题，按实际库存出题。 `:a.kind==='review'?'本卷含已曝光题，只作无提示复习；不计为新的独立后测或迁移证据。 ':!a.evidenceVersion?'历史卷未追踪题目曝光，保留成绩但不认证为未见题。 ':''}${isPractice(a)?'练习模式 · 确认本题后显示解析，提示使用单独记录':'独立检测中 · 结构标签、答案联动与助教已关闭，整套提交后显示解析'}</div>
   ${isPractice(a)&&a.reasons[q.id]?`<div class="al-selection-reason"><span>✦</span><div><strong>这一题为什么适合你</strong><p>${esc(a.reasons[q.id].reason)}${a.reasons[q.id].repeated?' 这是已练过题目的复练，不计作新的题目证据。':''}</p></div></div>`:''}
   <div class="al-question-layout"><div class="al-observation ${practiceFootage?'al-with-footage':''}">${practiceFootage&&q.visual.kind==='facts'?'<div class="al-related-footage"></div>':''}<div class="al-media-root"></div>${practiceFootage&&q.visual.kind!=='facts'?'<div class="al-related-footage"></div>':''}${q.type==='hotspot'?'<p class="al-figure-help">点击图像放置定位点；拖动可平移。键盘可用方向键移动定位光标，回车确认。</p>':''}</div><section class="al-question-panel" aria-labelledby="al-question-title"><div class="al-question-labels"><span>${TYPES[q.type]}</span><span>${q.visual.kind==='ct'?'真实 CT 阅片':q.visual.kind==='frame'?'真实术野观察':'真实临床配图'}</span></div><h2 id="al-question-title" tabindex="-1">${esc(q.stem)}</h2><p class="al-answer-instruction">${q.type==='multi'?'请选择所有符合条件的选项。':q.type==='order'?'用上移、下移按钮排列完整顺序，确认后保存。':q.type==='hotspot'?'在图中点选目标，系统不会提前提示是否正确。':'选择一项最合适的答案。'}</p><div class="al-options"></div><div class="al-confidence"><p>你有多大把握？ <small>不计入分数</small></p><div>${[['low','需要核对'],['medium','基本确定'],['high','很有把握']].map(([id,label])=>`<button data-action="confidence" data-id="${id}" aria-pressed="${this.confidence===id}">${label}</button>`).join('')}</div></div><div class="al-hint" ${this.hints?'':'hidden'}>${this.hints?esc(q.hint):''}</div><div class="al-notice" role="status" hidden></div><div class="al-answer-actions"><button class="al-button al-primary" data-action="confirm">${isPractice(a)?'确认并查看解析':this.index<a.questionIds.length-1?'保存并下一题':'保存本题'}</button><button class="al-text-button" data-action="uncertain">暂时不确定</button>${isPractice(a)?'<button class="al-text-button" data-action="hint">✦ 给我一个观察提示</button>':''}</div></section></div>
   <footer class="al-question-footer"><div class="al-question-map" aria-label="题目导航">${a.questionIds.map((id,i)=>`<button data-action="page" data-index="${i}" class="${i===this.index?'active':''} ${a.responses[id]?'saved':''}" aria-label="第 ${i+1} 题${a.responses[id]?'，已保存':''}" ${i===this.index?'aria-current="step"':''}>${i+1}</button>`).join('')}</div>${!isPractice(a)?`<button class="al-button al-submit" data-action="submit" ${count===a.questionIds.length?'':'disabled'}>整套提交 · 查看分析</button>`:''}</footer></div>`);
  this.renderOptions();this.mountMedia(q,false);if(practiceFootage)this.mountFootage(q,true);this.root.querySelector('#al-question-title')?.focus({preventScroll:true});
 }
 mountMedia(q,review,pick=null){this.media=new AssessmentMedia();this.media.mount(this.root.querySelector('.al-media-root'),q,{review,pick:pick??(q.type==='hotspot'&&Array.isArray(this.choice)?this.choice:null),onPick:point=>{if(review)return;this.choice=point;this.updateDraft();this.updateInputs();},onReady:(ready,error)=>{if(ready){recordExposure(this.session,q,review?'answer':'asset',review?null:this.attempt);this.api.save();}this.mediaReady=ready;this.updateInputs();if(error)this.notice(error);},onInteract:action=>{if(!this.attempt||review)return;this.interactions ||= {};this.interactions[action]=(this.interactions[action]||0)+1;}});}
 mountFootage(q,practice=false){
  const root=this.root.querySelector('.al-related-footage'),clip=footageForQuestion(q);if(!root||!clip)return;
  this.footage=new TrainingFootage(root,{clip,compact:true,switchable:false,onLearn:data=>{
   this.log('footage_view',{question:q.id,...data});
   if(practice&&this.attempt&&this.view==='question'&&!this.attempt.reviewed.includes(q.id)&&!this.attempt.drafts?.[q.id]?.footageViewed){
    this.hints++;this.updateDraft();this.attempt.drafts[q.id].footageViewed=true;this.api.save();
    const box=this.root.querySelector('.al-hint');if(box){box.hidden=false;box.textContent='已查看术野参考，本题按辅助练习记录。';}
   }
  }});
 }
 renderOptions(){
  const q=this.q,a=this.attempt,root=this.root.querySelector('.al-options');if(!root)return;
  if(q.type==='hotspot')root.innerHTML='<div class="al-point-status" role="status"></div>';
  else if(q.type==='order')root.innerHTML=`<ol class="al-order-list">${(Array.isArray(this.choice)?this.choice:shuffled(q.options.map(o=>o.id),a.seed+this.index)).map((id,i)=>`<li><span>${i+1}</span><p>${esc(q.options.find(o=>o.id===id).text)}</p><div><button data-action="order" data-id="${id}" data-direction="up" aria-label="上移：${esc(q.options.find(o=>o.id===id).text)}" ${i===0?'disabled':''}>↑</button><button data-action="order" data-id="${id}" data-direction="down" aria-label="下移：${esc(q.options.find(o=>o.id===id).text)}" ${i===q.options.length-1?'disabled':''}>↓</button></div></li>`).join('')}</ol>`;
  else root.innerHTML=shuffled(q.options,a.seed+this.index*31).map((o,i)=>`<button class="al-option" data-action="answer" data-id="${o.id}" aria-pressed="false"><span class="al-option-symbol">${q.type==='multi'?'□':String.fromCharCode(65+i)}</span><span>${esc(o.text)}</span></button>`).join('');
  this.updateInputs();
 }
 choose(id){if(this.q.type==='multi'){const choice=Array.isArray(this.choice)?this.choice:[];this.choice=choice.includes(id)?choice.filter(v=>v!==id):[...choice,id];}else this.choice=id;this.updateDraft();this.updateInputs();}
 updateDraft(){this.attempt.drafts ||= {};this.attempt.drafts[this.q.id]={...this.attempt.drafts[this.q.id],value:this.choice,confidence:this.confidence,hints:this.hints,elapsedMs:this.elapsedPrior+performance.now()-this.started};this.api.save();}
 updateInputs(){
  if(!this.q)return;this.root.querySelectorAll('[data-action="answer"]').forEach(b=>b.setAttribute('aria-pressed',String(Array.isArray(this.choice)?this.choice.includes(b.dataset.id):this.choice===b.dataset.id)));
  this.root.querySelectorAll('[data-action="confidence"]').forEach(b=>b.setAttribute('aria-pressed',String(this.confidence===b.dataset.id)));
  const confirm=this.root.querySelector('[data-action="confirm"]');if(confirm)confirm.disabled=!this.mediaReady||!validAnswer(this.q,this.choice);
  const point=this.root.querySelector('.al-point-status');if(point)point.textContent=this.choice==='uncertain'?'已选择暂时不确定':Array.isArray(this.choice)?'定位点已放置，确认后保存':'等待在图中放置定位点';
  const uncertain=this.root.querySelector('[data-action="uncertain"]');uncertain?.setAttribute('aria-pressed',String(this.choice==='uncertain'));
 }
 showHint(){if(!isPractice(this.attempt)||this.attempt.reviewed.includes(this.q.id))return;this.hints++;const box=this.root.querySelector('.al-hint');box.hidden=false;box.textContent=this.hints===1?this.q.hint:skillFor(this.q).lesson.slice(0,2).join(' ');this.updateDraft();this.log('hint',{attempt:this.attempt.id,question:this.q.id,level:Math.min(this.hints,2),learningOnly:true});}
 confirm(){
  const a=this.attempt,q=this.q;
  const r=saveResponse(a,q,this.choice,{confidence:this.confidence,hints:this.hints,elapsedMs:this.elapsedPrior+performance.now()-this.started,mediaReady:this.mediaReady});
  if(a.drafts)delete a.drafts[q.id];this.log('response',{attempt:a.id,kind:a.kind,question:q.id,skill:q.skill,confidence:r.confidence,hints:r.hints,answer:r.value,elapsedMs:r.elapsedMs,observationActions:this.interactions||{}});this.interactions={};
  if(isPractice(a)){reviewPractice(a,q);this.api.save();return this.renderPracticeFeedback();}
  if(this.index<a.questionIds.length-1)this.index++;this.renderQuestion();if(Object.keys(a.responses).length===a.questionIds.length)this.notice('全部答案已保存。可以检查后整套提交。');
 }
 feedbackMarkup(q,r){const correct=correctAnswer(q,r.value),s=skillFor(q),values=Array.isArray(r.value)?r.value:[r.value];
  return `<div class="al-feedback-heading ${correct?'correct':'incorrect'}"><span>${correct?'✓':'↻'}</span><div><h2>${correct?(r.hints?'提示后完成':'本题判断正确'):'找到一个需要澄清的地方'}</h2><p>${esc(misconception(q,r))}${!correct&&r.confidence==='high'?' · 高信心错误，优先复练':''}</p></div></div><div class="al-answer-comparison"><div><small>你的判断</small><p>${esc(answerText(q,r.value))}</p></div><div><small>参考答案</small><p>${q.type==='hotspot'?'图中绿色细轮廓所示区域':esc(answerText(q,q.answer))}</p></div></div><p class="al-explanation">${esc(q.explanation)}</p>${q.type!=='hotspot'&&q.type!=='order'?`<div class="al-option-feedback">${q.options.filter(o=>values.includes(o.id)||(!correct&&(Array.isArray(q.answer)?q.answer.includes(o.id):q.answer===o.id))).map(o=>`<p><strong>${values.includes(o.id)?'已选':'漏选 / 应选'} · ${esc(o.text)}</strong><span>${esc(o.feedback||q.explanation)}</span></p>`).join('')}</div>`:''}<div class="al-repair"><p class="al-mini">把理解补完整</p><h3>${s.goal}</h3><ol>${s.lesson.map(x=>`<li>${esc(x)}</li>`).join('')}</ol></div><details class="al-question-sources"><summary>本题依据与延伸阅读</summary>${refLinks(q.source)}</details>`;
 }
 renderPracticeFeedback(){const a=this.attempt,q=this.bank.find(q=>q.id===a.questionIds[this.index]),r=a.responses[q.id];this.q=q;this.choice=r.value;recordExposure(this.session,q,'answer',a);this.api.save();
  this.frame(`<div class="al-exam"><header class="al-exam-top"><div><p class="al-mini">FEEDBACK · 学会再向前一步</p><h1>${attemptName(a)} · ${this.index+1}/${a.maxQuestions}</h1></div><button class="al-button" data-action="pause">保存并稍后继续</button></header><div class="al-question-layout"><div class="al-observation"><div class="al-media-root"></div>${footageForQuestion(q)?'<div class="al-related-footage"></div>':''}</div><section class="al-question-panel">${this.feedbackMarkup(q,r)}<div class="al-notice" role="status" hidden></div><button class="al-button al-primary" data-action="next-practice">${a.questionIds.length>=a.maxQuestions?'完成本组 · 查看学习画像':'根据本题表现，安排下一题'} →</button></section></div></div>`);this.mountMedia(q,true,r.value);this.mountFootage(q);}
 finish(){const a=this.attempt;const result=finishAttempt(a,this.bank,this.session);this.view='result';this.api.lock(false);this.log('submit',{attempt:a.id,kind:a.kind,result});this.renderResult();}
 renderResult(){
  const a=this.attempt;if(!a?.submitted)return;this.view='result';const r=a.result,profile=learnerProfile(this.session,this.bank),weak=[...profile].sort((x,y)=>y.priority-x.priority).slice(0,3),first=ensureLab(this.session).attempts.find(x=>x.submitted&&(x.sourceKind||x.kind)===(a.sourceKind||a.kind)&&x.bankVersion===a.bankVersion),errors=r.details.filter(x=>!x.correct),high=a.questionIds.filter(id=>!correctAnswer(this.bank.find(q=>q.id===id),a.responses[id].value)&&a.responses[id].confidence==='high').length;
  this.frame(`<div class="al-result"><header class="al-result-hero"><div><p class="al-kicker">LEARNING INSIGHT · ${this.session.kind==='demo'?'教师演示记录':'本次真实作答'}</p><h1>${errors.length?'找准薄弱点，下一次更有依据。':'本组完成，换个情境再验证。'}</h1><p>${attemptName(a)} · ${new Date(a.submitted).toLocaleString('zh-CN',{hour12:false})}</p><div class="al-result-score"><strong>${r.score}</strong><span>/ 100<b>${r.correct} / ${r.count} 题正确</b></span></div></div><div class="al-result-metrics"><div><span>无提示答对</span><strong>${r.independentCorrect}<small>题</small></strong></div><div><span>使用提示</span><strong>${r.assistedCount}<small>题</small></strong></div><div><span>关键安全项</span><strong>${r.criticalCount?`${r.criticalCorrect}/${r.criticalCount}`:'未涉及'}</strong></div><div><span>高信心错误</span><strong>${high}<small>题</small></strong></div></div></header><div class="al-result-actions"><button class="al-button al-primary" data-action="start" data-kind="adaptive">✦ 按薄弱点定向复练</button><button class="al-button" data-action="start" data-kind="retry">换题迁移复测</button><button class="al-button" data-action="export">导出学习报告</button><button class="al-button" data-action="print">打印 / PDF</button><button class="al-text-button" data-action="hub">回检测中心</button></div>
   ${insightMarkup(learningSnapshot(this.session,this.bank),{id:'al-result-dimensions',heading:'累计多维学习画像'})}
   <div class="al-insight-grid"><article class="al-skill-panel">${this.profileMarkup(profile)}</article><aside class="al-coach"><span class="al-ai-icon">✦</span><p class="al-mini">针对你的教学建议</p><h3>先澄清错因，再检验迁移</h3>${weak.map((s,i)=>`<div class="al-next-step"><span>0${i+1}</span><h3>${s.name}</h3><p>${esc(s.errors.at(-1)?.tag||(s.independent?'补充新情境中的独立作答证据':'本次尚未充分覆盖这个领域'))}</p><button class="al-text-button" data-action="lesson" data-skill="${s.id}">先看微课 →</button><button class="al-text-button" data-action="start" data-kind="adaptive" data-skill="${s.id}">针对这一点练 →</button></div>`).join('')}</aside></div>
   <section class="al-section"><div class="al-section-heading"><h2>逐题复盘</h2><p>点击题目，回到原图、原答案与详细解析</p></div><div class="al-review-list">${a.questionIds.map((id,i)=>{const q=this.bank.find(q=>q.id===id),d=r.details[i];return `<button data-action="review-question" data-index="${i}"><span class="al-review-number ${d.correct?'correct':'incorrect'}">${i+1}</span><div><strong>${esc(q.stem)}</strong><small>${skillFor(q).name} · ${esc(d.error)}${a.responses[id].confidence==='high'&&!d.correct?' · 高信心错误':''}</small></div><span>${d.correct?'答对':'复盘'} ↗</span></button>`;}).join('')}</div></section><details class="al-evidence"><summary>查看评价口径与版本</summary><p>本次按题等权计分，多选与排序完整正确才得分。使用提示单独记录；本组可确认的首次未见题无提示答对 ${r.firstUnseenCorrect??0} 题。${a.evidenceVersion?'同题复习不改变首次记录。':'历史卷曝光未知，不作未见题证明。'}${first!==a?`同类首次检测为 ${first.result.score} 分，原记录保留。`:''}不同模式、不同题目组合的分数不能直接等同比较；前后测等难度与教学效果尚未经过学生数据验证。</p><p>掌握估计采用本地知识追踪，仅用于安排练习。${BANK_VERSION} · 数据仅保存在本机。</p></details></div>`);
 }
 renderReview(){const a=this.attempt,i=this.reviewIndex||0,q=this.bank.find(q=>q.id===a.questionIds[i]),r=a.responses[q.id];if(!a.submitted)return;this.view='review';this.q=q;this.choice=r.value;recordExposure(this.session,q,'answer',a);this.api.save();
  this.frame(`<div class="al-exam"><header class="al-exam-top"><div><p class="al-mini">REVIEW · 第 ${i+1}/${a.questionIds.length} 题</p><h1>${esc(q.stem)}</h1></div><button class="al-button" data-action="result-back">回到学习画像</button></header><div class="al-question-layout"><div class="al-observation"><div class="al-media-root"></div>${footageForQuestion(q)?'<div class="al-related-footage"></div>':''}</div><section class="al-question-panel">${this.feedbackMarkup(q,r)}<div class="al-result-actions"><button class="al-button" data-action="review-question" data-index="${i-1}" ${i===0?'disabled':''}>上一题</button><button class="al-button" data-action="review-question" data-index="${i+1}" ${i===a.questionIds.length-1?'disabled':''}>下一题</button><button class="al-button al-primary" data-action="start" data-kind="adaptive" data-skill="${q.skill}">练习这一领域</button></div></section></div></div>`);this.mountMedia(q,true,r.value);this.mountFootage(q);}
 renderLesson(id){const s=SKILLS.find(s=>s.id===id);if(!s)return;this.view='lesson';this.api.lock(false);ensureLab(this.session).lessonViews.push({skill:id,at:new Date().toISOString()});this.log('lesson_open',{skill:id,learningOnly:true});
  const visualQ=this.bank.find(q=>q.id===(id==='segment'?'segment-3':id+'-5')&&practiceAvailable(this.session,this.bank,q))||this.bank.find(q=>q.skill===id&&practiceAvailable(this.session,this.bank,q));if(!visualQ)throw new Error('该领域的示例仍为检测保留题，请先完成对应检测。');recordExposure(this.session,visualQ,'lesson');this.api.save();
  this.q=visualQ;this.choice=null;
  this.frame(`<div class="al-lesson"><header class="al-lesson-heading"><button class="al-text-button" data-action="hub">← 检测中心</button><p class="al-mini">MICRO LESSON · ${s.short}</p><h1>${s.goal}</h1><p>先抓住关键关系，再到新情境里独立判断。</p></header><div class="al-question-layout"><div class="al-observation"><div class="al-media-root"></div>${footageForQuestion(visualQ)?'<div class="al-related-footage"></div>':''}${lessonDiagram(id)}<div class="al-lesson-path"><span>观察</span><b>→</b><span>解释依据</span><b>→</b><span>换题验证</span></div></div><article class="al-question-panel"><h2>${s.name} · 三个要点</h2><ol class="al-lesson-points">${s.lesson.map((text,i)=>`<li><span>0${i+1}</span><p>${esc(text)}</p></li>`).join('')}</ol><div class="al-repair"><h3>带着这个问题再看一次</h3><p>${esc(visualQ.stem)}</p><p>${esc(visualQ.explanation)}</p></div><div class="al-question-sources">${refLinks(s.source)}</div><div class="al-result-actions"><button class="al-button al-primary" data-action="start" data-kind="adaptive" data-skill="${id}">✦ 按这一点练习</button><button class="al-button" data-action="start" data-kind="retry" data-skill="${id}">关闭提示再测</button>${s.link?`<a class="al-button" href="${s.link}">打开完整学习场景 ↗</a>`:''}</div></article></div></div>`);this.mountMedia(visualQ,true);this.mountFootage(visualQ);}
 exportReport(){const a=this.attempt;if(!a?.submitted)return;const profile=learnerProfile(this.session,this.bank);const artifact={learningInsights:learningSnapshot(this.session,this.bank),sessionId:this.session.id,kind:this.session.kind,exportedAt:new Date().toISOString(),bankVersion:BANK_VERSION,model:MODEL,evidenceDate:EVIDENCE_DATE,attempt:a,profile,exposureVersion:ensureLab(this.session).exposureVersion,exposures:ensureLab(this.session).exposures,questions:a.questionIds.map(id=>{const q=this.bank.find(q=>q.id===id);return {id:q.id,skill:q.skill,stem:q.stem,chosen:answerText(q,a.responses[id].value),reference:q.type==='hotspot'?'来源图中定位区域':answerText(q,q.answer),explanation:q.explanation,sources:q.source.map(id=>REFERENCES[id])};})};this.api.download(JSON.stringify(artifact,null,2),`${this.session.id}_${attemptName(a)}.json`,'application/json;charset=utf-8');}
 reportSummary(){const {doneCount,last}=assessmentReportSummary(this.session);return `<div class="task-card"><p class="eyebrow">图文检测与 AI 学习画像</p><h2>${last?`${attemptName(last)} · ${last.result.score} 分`:'真实影像与八维能力检测'}</h2><p style="margin-top:9px">${last?`当前题库已完成 ${doneCount} 次检测或复练；最近一次无提示答对 ${last.result.independentCorrect}/${last.result.count} 题，其中可确认首次未见题 ${last.result.firstUnseenCorrect??0} 题。`:'完成检测后，在这里汇总独立表现和定向复练记录。'}</p><div class="actions"><button id="open-intelligent-assessment" class="primary">查看检测与多维画像 →</button><button id="open-report-knowledge" class="outline">知识图谱 ↗</button></div></div>`;}
}
