/** Guided three-screen exploration. Observational stations on real CT-004.
 * Vessel/airway trees are whole meshes — not branch-level gold standards.
 * Operative stills are a different patient from CT-004.
 */
export const EXPLORE_CASE='CT-004';
export const EXPLORE_VERSION='EX-2026.09.13-1';

export const COMPARE_CASES=[
 {id:'CT-004',title:'右上叶结节',use:'本课主例 · 源网格含 RS1–RS3 与五叶'},
 {id:'CT-006',title:'右肺结节',use:'库内唯一同时提供 RS4 与 RS5 的病例'},
 {id:'CT-007',title:'右下叶结节',use:'右下叶对照 · 不要把后方都叫 S2'},
 {id:'CT-002',title:'左上叶结节',use:'左上叶 S1+2 / 舌段对照'},
 {id:'CT-012',title:'左下叶结节',use:'库内左下叶主诉例'},
];

export const SCREEN_LEGEND=[
 {id:'ct',num:'01',name:'真实 CT',hint:'滚轮逐层 · 轴/冠/矢 · 肺窗/纵隔窗 · HU · 测距'},
 {id:'anatomy',num:'02',name:'真实三维',hint:'本例源网格 · 拖动旋转 · 点击定位到同一空间点'},
 {id:'scope',num:'03',name:'局部真实三维',hint:'同一病例近景 · 不是术中腔镜 · 真术野在独立页'},
];

export const STATIONS=[
 {
  id:'orient',
  num:'01',
  title:'先认患者，再看屏幕',
  kicker:'方位',
  goal:'建立 DICOM 患者坐标。屏幕左右不是你的左右。',
  screen:'ct',
  drive:{caseId:'CT-004',plane:'axial',window:'lung',camera:'anterior',select:null,segments:false,labels:true,locate:null},
  coach:{
   ct:'看画面四边的 R / L / A / P。轴位按从足侧向头侧观察。',
   anatomy:'三维旋转不会改 CT 的患者坐标。定位十字仍是同一个空间点。',
   scope:'局部屏跟随当前选中点，不是另一套左右约定。',
  },
  do:'在真实 CT 上切换轴位，读方向字母。不要用自己的左右代替患者。',
  note:'本库 CT 已裁剪、重采样，层间距约 2 mm。方向字母指向患者，不指向观察者。',
  question:'常规胸部轴位从足侧向头侧观察。屏幕左侧对应哪一侧？',
  options:['患者右侧','患者左侧','与左右无关，只表示屏幕位置'],
  answer:0,
  why:'按本课固定坐标约定，轴位屏幕左侧为患者右侧。先读 R / L，再命名肺叶或肺段。',
  hint:['先找方向字母，不要用自己的左手。','R 标记所在一侧是患者右侧。'],
  pick:null,
  figures:[],
  compare:[],
  mnemonic:null,
 },
 {
  id:'window',
  num:'02',
  title:'肺窗看实质，纵隔窗看纵隔',
  kicker:'窗位',
  goal:'用数值窗宽窗位观察同一层真实 HU，而不是“调亮一点”。',
  screen:'ct',
  drive:{caseId:'CT-004',plane:'axial',window:'lung',camera:'anterior',select:'s01',segments:false,labels:true,locate:'nodule'},
  coach:{
   ct:'默认肺窗 WW 1500 / WL −600。切到纵隔窗 WW 400 / WL 40。点击层面读 HU。',
   anatomy:'三维中的半透明切面应与当前 CT 层一致。',
   scope:'近景放大的是同一病例网格，不是另一窗宽的假图。',
  },
  do:'按“定位病灶”，在肺窗观察结节与血管支气管，再切纵隔窗。测距只给出几何长度，不代替临床 T 分期。',
  note:'本库为非增强重采样 CT，界面不讲强化。像素间距写在 CT 状态栏。',
  question:'要观察肺实质与支气管血管树，应优先使用哪一窗？',
  options:['肺窗（约 WW 1500 / WL −600）','纵隔窗（约 WW 400 / WL 40）','骨窗（约 WW 1800 / WL 400）'],
  answer:0,
  why:'肺窗拉开含气肺实质的对比。纵隔窗用于纵隔与软组织；骨窗用于骨性结构。窗值可在界面改，改了要读出数字。',
  hint:['看 CT 屏右下角的 WW / WL 数字。','肺窗是观察含气肺和支气管血管的常用起点。'],
  pick:{ids:['s01'],names:['结节'],groups:['nodule'],label:'源结节标注'},
  figures:[],
  compare:[],
  mnemonic:null,
 },
 {
  id:'lobes',
  num:'03',
  title:'五叶之中，先找到右上叶',
  kicker:'肺叶',
  goal:'在真实三维点选右上叶，并在 CT 上看到同一结构的轮廓。',
  screen:'anatomy',
  drive:{caseId:'CT-004',plane:'axial',window:'lung',camera:'anterior',select:'s12',segments:false,labels:true,locate:null},
  coach:{
   ct:'选中后，当前层会画出该肺叶源网格的轮廓。轮廓是投影，不是天然叶间裂。',
   anatomy:'点击右上叶网格。颜色是结构编码，不是术中颜色。',
   scope:'局部屏拉近同一叶。换前方 / 后方预设，确认它不会跟着屏幕左右改名。',
  },
  do:'在结构目录或三维屏点选「右上叶」。观察水平裂与斜裂的相对位置，而不是只看它在屏幕哪一侧。',
  note:'CT-004 提供五叶源网格。右中叶位于水平裂与斜裂之间的前方区域。',
  question:'位于右肺水平裂上方的教学肺叶是哪一叶？',
  options:['右上叶','右中叶','左上叶'],
  answer:0,
  why:'右上叶在水平裂上方。屏幕左右随视角改变，肺裂和肺门才是定向依据。',
  hint:['先找水平裂，再判断它的上方是哪一叶。','右中叶夹在水平裂与斜裂之间的前方。'],
  pick:{ids:['s12','rul'],names:['右上叶'],groups:[],label:'右上叶'},
  figures:[],
  compare:[],
  mnemonic:null,
 },
 {
  id:'segments',
  num:'04',
  title:'右上叶 S1 / S2 / S3',
  kicker:'肺段',
  goal:'打开本例源肺段网格，对照真实配图，而不是背一张扇形分区图。',
  screen:'ct',
  drive:{caseId:'CT-004',plane:'axial',window:'lung',camera:'posterior',select:'s08',segments:true,labels:true,locate:null},
  coach:{
   ct:'彩色区来自本例已提供的闭合肺段网格，按同一 CT 体素取样。可对照未着色配图。',
   anatomy:'图层中打开肺段。RS1a/b、RS2a/b、RS3a/b 是源亚段名，不要改写成未提供的标签。',
   scope:'后方视角帮助区分上叶后段与下叶背段的空间，不能只凭“在后面”。',
  },
  do:'对照下方三张真实配图（填色 / 未着色）。在连续层面看 RS2 的出现与消失，不要把所有背侧区域都叫 S6。',
  note:'CT-004 仅提供右上叶源段。右中叶 S4/S5 请换到 CT-006，不要在本例上推测中叶段界。',
  question:'右上叶 S2 的规范名称是？',
  options:['后段','尖段','前段','下叶背段'],
  answer:0,
  why:'右上叶 S1 尖段、S2 后段、S3 前段。下叶背段是 S6，虽可同在胸腔后方，但不属于上叶。',
  hint:['编号必须和侧别、肺叶一起读。','S6 是下叶背段，不能因为都在后方就与 S2 互换。'],
  pick:{ids:['s06','s07','s08','s09','s10','s11','s1','s2','s3'],names:['RS1a','RS1b','RS2a','RS2b','RS3a','RS3b'],groups:['segment'],label:'右上叶源肺段'},
  figures:[
   {src:'./segment-atlas/figures/RS1.webp',plain:'./segment-atlas/figures/RS1-unmarked.webp',caption:'RS1 尖段 · 真实断层 + 源网格投影'},
   {src:'./segment-atlas/figures/RS2.webp',plain:'./segment-atlas/figures/RS2-unmarked.webp',caption:'RS2 后段 · 红圈为病灶外留白，不是切缘'},
   {src:'./segment-atlas/figures/RS3.webp',plain:'./segment-atlas/figures/RS3-unmarked.webp',caption:'RS3 前段 · 覆盖不等于天然解剖线'},
  ],
  compare:['CT-006','CT-007'],
  mnemonic:'记忆线索（须在本例连续层面核对，不是金标准）：先定叶，再沿段支气管由近端向外周追踪。',
 },
 {
  id:'airway',
  num:'05',
  title:'上叶支气管，和必须留下的通路',
  kicker:'气道',
  goal:'在三屏追踪支气管整树：目标通向右上叶，中间支气管仍通向中、下叶。',
  screen:'anatomy',
  drive:{caseId:'CT-004',plane:'axial',window:'lung',camera:'anterior',select:'s03',segments:false,labels:true,locate:null},
  coach:{
   ct:'沿连续层面追踪管腔，不要凭一个圆形截面命名。本例未逐支标定 B1/B2/B3。',
   anatomy:'源网格名称是「支气管」整树。看它离开上叶后是否还向尾侧延续。',
   scope:'局部放大分叉。分叉以远仍供应保留肺时，不能随上叶一起处理。',
  },
  do:'在 CT 找到支气管截面，三维查看整树走行，局部屏看分叉。本站考察关系，不把整树点击自动判成某一支。',
  note:'源资料将支气管按整树导出。教程中的分支号是解剖学习索引，不是对本例每根分支的自动确认。',
  question:'右上叶支气管离开右主支气管后，通向中叶和下叶的通气通路是？',
  options:['中间支气管','把上叶支气管当作唯一需要保留的结构','左主支气管'],
  answer:0,
  why:'右上叶支气管发出后，中间支气管继续通向中、下叶。误处理影响保留肺通气。本例网格是整树，具体分支须结合连续影像逐例辨认。',
  hint:['问它还通向哪些肺叶，而不只问“是不是支气管”。','向尾侧延续并发出中、下叶支气管的是中间支气管。'],
  pick:{ids:['s03','rub','bi','rmb'],names:['支气管'],groups:['airway'],label:'支气管整树'},
  figures:[],
  compare:[],
  mnemonic:null,
 },
 {
  id:'vessels',
  num:'06',
  title:'目标静脉，和必须留下的回流',
  kicker:'血管',
  goal:'区分灌注与回流。上叶目标旁可能汇入中叶静脉，不能把汇合段整体离断。',
  screen:'anatomy',
  drive:{caseId:'CT-004',plane:'axial',window:'mediastinum',camera:'anterior',select:'s05',segments:false,labels:true,locate:null},
  coach:{
   ct:'纵隔窗有助于看肺门管道的截面，仍要回到连续层面。',
   anatomy:'先点「肺静脉」整树，再点「肺动脉」整树。蓝色/红色是教学编码。',
   scope:'近景看汇合关系。未点名的细分支一律当作待核，不评分。',
  },
  do:'在三维分别显示肺静脉与肺动脉。理解：动脉承担灌注，静脉承担回流；开放损伤、误闭静脉、误闭动脉是三种机制。',
  note:'本例动静脉都是整树网格。中叶静脉汇入存在个体变异（三维研究，2025）。没有作者点名表时，不把点击某根管子判成检查点得分。',
  question:'上叶静脉目标旁还可能汇入中叶回流时，最安全的做法是？',
  options:['确认目标分支，并保留中叶回流','把整个汇合段当作上叶一键离断目标','只按颜色处理所有同色血管'],
  answer:0,
  why:'上叶切除仍需保护余肺引流。颜色不能代替起源、走行和供应/回流区域。变异须逐例辨认。',
  hint:['沿汇合处向外追踪，看还有哪一肺叶引流至此。','同色只是图层编码，不是离断许可。'],
  pick:{ids:['s05','s04','rulv','rmlv','a13','interlobar'],names:['肺静脉','肺动脉'],groups:['vein','artery'],label:'肺门管道整树'},
  figures:[],
  compare:[],
  mnemonic:null,
 },
 {
  id:'blind',
  num:'07',
  title:'关掉名称，换一个视角再认',
  kicker:'迁移',
  goal:'隐藏结构名，转到后方，仍能用肺门与肺裂找回右上叶。',
  screen:'anatomy',
  drive:{caseId:'CT-004',plane:'axial',window:'lung',camera:'posterior',select:null,segments:false,labels:false,locate:null},
  coach:{
   ct:'名称可以关，方向字母不要关。',
   anatomy:'使用「后方」预设。患者左右不随镜头翻转。',
   scope:'迷向时回到标准观察位，而不是猜颜色。',
  },
  do:'本站已关闭结构名称并切到后方。在三维再点出右上叶。不确定就暂停，这是安全行为。',
  note:'正式测验会同时关闭答案联动、结构名称和助教。探索阶段的点击不计错。',
  question:'腔镜或三维转到后外侧、画面左右改变后，应如何重新定向？',
  options:['结合肺门、肺裂与患者方向','沿用原来的屏幕左右','只按一种颜色猜测'],
  answer:0,
  why:'摄像机转动不能改变患者自身的左右。回到解剖标志，再关闭标签从新视角辨认。',
  hint:['先恢复标准观察位，再命名。','肺门和肺裂比屏幕左右可靠。'],
  pick:{ids:['s12','rul'],names:['右上叶'],groups:[],label:'右上叶'},
  figures:[],
  compare:[],
  mnemonic:null,
 },
 {
  id:'field',
  num:'08',
  title:'局部三维不是术中腔镜',
  kicker:'术野对照',
  goal:'分清三件事：本例 CT、本例重建、另一患者的公开术野。',
  screen:'scope',
  drive:{caseId:'CT-004',plane:'axial',window:'lung',camera:'anterior',select:'s04',segments:false,labels:true,locate:null},
  coach:{
   ct:'CT-004 是匿名右上叶结节病例。',
   anatomy:'源网格与 CT 共用 DICOM LPS 毫米坐标。',
   scope:'这一格是同一病例的局部真实三维。椭圆暗角的假腔镜已退出主屏。',
  },
  do:'看完第三屏的近景后，打开真实术野页对照“先看清再处理”的原则。不要把左上叶公开片说成本例右上叶手术。',
  note:'主线术野取自去标识化公开教学录像中的左上肺叶切除肺门游离；圆形光学对照来自另一台 RS8。画面未标注的分支编号一律 uncertain。本包没有误切喷血的真实切片。',
  question:'本页第三屏与公开术野录像是什么关系？',
  options:['第三屏是本例局部三维；术野是另一患者的公开教学片，只对照原则','三屏与术野是同一位患者的同一台手术','可以用带暗角的假腔镜画面代替真实术野'],
  answer:0,
  why:'没有同一患者的右上叶术野时，必须写清“不是同一人”。原则可以对照，空间不能假装配准。',
  hint:['看术野页的来源说明，不要把侧别和术式拼成一台手术。','第三屏标题是局部真实三维，不是腔镜。'],
  pick:null,
  figures:[
   {src:'./or-field/clean/posters/step01.jpg',plain:null,caption:'显露肺门 · 左上叶公开片 · 非 CT-004'},
   {src:'./or-field/clean/posters/step02.jpg',plain:null,caption:'管道游离 · 观察分叉与后方通道'},
   {src:'./or-field/clean/posters/step03.jpg',plain:null,caption:'闭合就位 · 器械进入不等于可以击发'},
   {src:'./or-field/clean/posters/step04.jpg',plain:null,caption:'圆形视野对照 · 另一患者、另一术式'},
  ],
  compare:[],
  mnemonic:null,
  fieldLink:'./or-field.html',
 },
];

export const stationById=id=>STATIONS.find(s=>s.id===id);
export const pickMatches=(station,payload={})=>{
 const rule=station?.pick;if(!rule)return false;
 const id=payload.id||payload.structure||'';
 const name=payload.name||'';
 const group=payload.group||'';
 if(rule.ids.includes(id)||rule.names.includes(name))return true;
 if(rule.names.length)return false;
 return rule.groups.includes(group);
};
