import {SKILLS} from './assessment-data.js';
import {KNOWLEDGE_MEDIA,DOMAIN_COLORS} from './knowledge-media.js';
import {htmlEscape as esc} from './learning-insights.js';

export async function loadKnowledgeLibrary(){
 const response=await fetch('./knowledge-library.json');
 if(!response.ok)throw new Error('知识正文加载失败，请重试。');
 const library=await response.json();
 if(library.nodes?.length!==16||!library.sources?.length)throw new Error('知识内容不完整，请重新加载。');
 return library;
}
export function topicText(topic,library){
 const sources=topic.references.map(id=>library?.sources.find(s=>s.id===id)).filter(Boolean);
 return [topic.summary,...topic.sections.flatMap(s=>[s.title,...s.points]),...topic.pitfalls,...topic.workflow,topic.scenario.stem,topic.scenario.discussion,...topic.takeaways,...sources.flatMap(s=>[s.title,s.supports])].join(' ').toLowerCase();
}
export function libraryStats(library){
 const media=Object.values(KNOWLEDGE_MEDIA).flat();
 return {topics:library.nodes.length,sections:library.nodes.reduce((n,t)=>n+t.sections.length,0),points:library.nodes.reduce((n,t)=>n+t.sections.reduce((v,s)=>v+s.points.length,0),0),images:new Set(media.map(m=>m.src)).size,videos:new Set(media.map(m=>m.video).filter(Boolean)).size,sources:new Set(library.sources.map(s=>s.url)).size};
}
const sourceLabel=(library,id)=>'S'+String(library.sources.findIndex(s=>s.id===id)+1).padStart(2,'0');
const sourceLinks=(library,ids)=>`<div class="kl-citations">${ids.map(id=>{const s=library.sources.find(s=>s.id===id);return s?`<a href="${esc(s.url)}" target="_blank" rel="noopener" title="${esc(s.title)}">${sourceLabel(library,id)} · ${esc(s.type||'来源')} ↗</a>`:'';}).join('')}</div>`;
export function figureMarkup(item,nodeId,index){return `<figure class="kl-figure"><button class="kl-image-button" data-kg-image="${esc(nodeId)}:${index}" aria-label="放大：${esc(item.title)}"><img src="${esc(item.src)}" alt="${esc(item.title)}" loading="lazy" decoding="async"><span>＋ 查看完整影像</span></button><figcaption><strong>${esc(item.title)}</strong><p>${esc(item.caption)}</p><small>${esc(item.credit)}${item.license?' · '+esc(item.license):''} · <a href="${esc(item.source)}" target="_blank" rel="noopener">影像来源 ↗</a></small></figcaption></figure>`;}

export function heroMarkup(){return `<div class="kl-image-ribbon" aria-label="知识库影像入口">${[['segment-name','CT 与肺段','读懂空间解剖'],['vessels-preserve','真实术野','连接结构与安全'],['staging-tissue','PET / CT','核对分期证据'],['fitness-diffusion','肺功能评估','理解多维储备']].map(([id,title,label])=>{const item=KNOWLEDGE_MEDIA[id][0],skill=({ 'segment-name':'segment','vessels-preserve':'vessels','staging-tissue':'staging','fitness-diffusion':'fitness'})[id];return `<button data-kg-read="${id}" style="--domain:${DOMAIN_COLORS[skill]}"><img src="${esc(item.src)}" alt="${esc(item.title)}" decoding="async"><span><small>${title}</small><strong>${label} <b>↗</b></strong></span></button>`;}).join('')}</div>`;}

export function catalogMarkup(library,nodes){return `<section class="kl-catalog" id="kg-catalog"><header class="kl-section-heading"><div><p class="kg-kicker">EXPLORE THE LIBRARY</p><h2>从一张影像，深入一个问题。</h2></div><p>8 个领域 · 16 个章节 · 点击卡片阅读完整图解</p></header><div class="kl-catalog-grid">${nodes.map((n,i)=>{const topic=library.nodes.find(t=>t.id===n.id),skill=SKILLS.find(s=>s.id===n.skill),item=KNOWLEDGE_MEDIA[n.id][0];return `<button class="kl-topic-card" data-kg-read="${n.id}" data-kg-card="${n.id}" style="--domain:${DOMAIN_COLORS[n.skill]}"><div class="kl-card-image"><img src="${esc(item.src)}" alt="${esc(item.title)}" loading="lazy" decoding="async"><span>${String(i+1).padStart(2,'0')}</span><em>${esc(skill.name)}</em></div><div class="kl-card-body"><h3>${n.title}<b>↗</b></h3><p>${esc(n.description)}</p><ul>${topic.sections.map(s=>`<li>${esc(s.title)}</li>`).join('')}</ul><footer><span>${KNOWLEDGE_MEDIA[n.id].length} 幅影像</span><span>${topic.references.length} 条来源</span><span>情境推演</span></footer></div></button>`;}).join('')}</div><p class="kl-catalog-empty" hidden>没有匹配的章节，试试“淋巴结”“DLCO”或“切缘”。</p></section>`;}

function diagramMarkup(topic){
 const d=topic.diagram;if(!d)return '';
 if(d.type==='risk-bands')return `<section class="kl-diagram"><p class="kg-kicker">FUNCTIONAL RISK STRATA</p><h3>${esc(d.title)}</h3><div class="kl-risk-bands">${d.bands.map(b=>`<div style="--band:${esc(b.color)}"><strong>${esc(b.label)}</strong><span>${esc(b.level)}</span></div>`).join('')}</div><p class="kl-diagram-caption">${esc(d.caption)}</p></section>`;
 if(d.type==='trial-comparison')return `<section class="kl-diagram"><p class="kg-kicker">EVIDENCE IN CONTEXT</p><h3>${esc(d.title)}</h3><div class="kl-trial-grid">${d.metrics.map(m=>`<article><h4>${esc(m.trial)}</h4><p>${esc(m.endpoint)}</p>${m.values.map((v,i)=>`<div class="kl-trial-value"><span>${esc(m.groups[i])}</span><div><i style="width:${v}%;--bar-color:${i?'#eaa1ff':'#59dded'}"></i></div><b>${v}%</b></div>`).join('')}</article>`).join('')}</div><p class="kl-diagram-caption">${esc(d.caption)}</p></section>`;
 const parallel=['decision-gates','gas-exchange','station-coverage'].includes(d.type);
 return `<section class="kl-diagram"><p class="kg-kicker">CONNECT THE CONCEPTS</p><h3>${esc(d.title)}</h3><ol class="kl-flow-diagram ${parallel?'kl-parallel-concepts':''}">${d.labels.map((label,i)=>`<li style="--step-color:${['#5de3ec','#b69aff','#ffb76b','#78e5ad'][i%4]}"><span>${parallel?'◇':String(i+1).padStart(2,'0')}</span><strong>${esc(label)}</strong></li>`).join('')}</ol>${d.result?`<p class="kl-diagram-result">${esc(d.result)}</p>`:''}<p class="kl-diagram-caption">${esc(d.caption)}</p></section>`;
}
export function articleMarkup(library,node){
 const topic=library.nodes.find(n=>n.id===node.id),skill=SKILLS.find(s=>s.id===node.skill),media=KNOWLEDGE_MEDIA[node.id],video=media.find(m=>m.video);
 return `<article class="kl-article" id="kg-article" tabindex="-1" style="--domain:${DOMAIN_COLORS[node.skill]}" aria-labelledby="kg-article-title"><header class="kl-article-header"><div><p class="kg-kicker">CLINICAL KNOWLEDGE / ${esc(skill.short)}</p><h2 id="kg-article-title">${node.title}</h2><div class="kl-article-meta"><span>${esc(skill.name)}</span><span>3 个专题 · 9 条要点</span><span>${media.length} 幅配图${video?' · 1 段术野':''}</span></div></div><button data-kg-action="catalog">浏览全部章节 ↗</button></header><p class="kl-lead">${esc(topic.summary)}</p><nav class="kl-article-nav" aria-label="本节知识专题">${topic.sections.map((s,i)=>`<button data-kg-section="${i}"><span>0${i+1}</span>${esc(s.title)}</button>`).join('')}</nav><div class="kl-media-grid">${media.map((m,i)=>figureMarkup(m,node.id,i)).join('')}</div>${diagramMarkup(topic)}<div class="kl-reading-grid"><div class="kl-reading-main">${topic.sections.map((section,i)=>`<section class="kl-topic-section" id="kg-section-${i}" tabindex="-1"><div class="kl-topic-heading"><span>0${i+1}</span><h3>${esc(section.title)}</h3></div><ul>${section.points.map(point=>`<li>${esc(point)}</li>`).join('')}</ul>${sourceLinks(library,section.sources||[])}</section>`).join('')}</div><aside class="kl-study-guide"><section><p class="kg-kicker">THINK IN STEPS</p><h3>把知识用起来</h3><ol>${topic.workflow.map((step,i)=>`<li><span>0${i+1}</span><p>${esc(step)}</p></li>`).join('')}</ol></section><section class="kl-pitfalls"><p class="kg-kicker">COMMON PITFALLS</p><h3>这些地方容易混淆</h3><ul>${topic.pitfalls.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></section></aside></div>${video?`<section class="kl-video-section"><div><p class="kg-kicker">OBSERVE IN MOTION</p><h3>回到连续术野，观察空间关系。</h3><p>${esc(video.caption)}</p><small>本站既有教学片段 · ${esc(video.credit)} · <a href="${esc(video.source)}" target="_blank" rel="noopener">原课程与来源 ↗</a></small></div><video controls playsinline preload="none" poster="${esc(video.src)}" aria-label="${esc(video.title)}"><source src="${esc(video.video)}" type="video/mp4">当前浏览器不支持视频，请打开原课程查看。</video></section>`:''}<section class="kl-scenario"><div><p class="kg-kicker">CASE DISCUSSION</p><h3>带着一个病例，检验理解。</h3><p>${esc(topic.scenario.stem)}</p></div><details><summary>展开推理与讨论 <span>＋</span></summary><p>${esc(topic.scenario.discussion)}</p>${sourceLinks(library,topic.scenario.sources||[])}</details></section><section class="kl-takeaways"><h3>离开本节前，记住这三点。</h3><ol>${topic.takeaways.map((s,i)=>`<li><span>0${i+1}</span>${esc(s)}</li>`).join('')}</ol></section><section class="kl-topic-sources"><header><div><p class="kg-kicker">READ THE ORIGINAL EVIDENCE</p><h3>本节依据与延伸阅读</h3></div><span>核对日期 ${esc(library.checked)}</span></header>${topic.references.map(id=>sourceCard(library,library.sources.find(s=>s.id===id))).join('')}</section><footer class="kl-article-footer"><p>阅读与测评分别记录。后续相关题目会注明已学习，掌握程度由作答证据更新。</p><button class="primary" data-kg-action="practice">进入本领域练习 ↗</button></footer></article>`;
}
function sourceCard(library,s){if(!s)return '';return `<article class="kl-source-card"><span>${sourceLabel(library,s.id)}</span><div><small>${esc(s.year||'课程')} · ${esc(s.type||'资料')}</small><h4><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)} ↗</a></h4><p>${esc(s.supports||s.scope||'本节知识与学习方法。')}</p>${s.accessNote||s.access?`<details><summary>查阅范围</summary><p>${esc(s.accessNote||s.access)}</p></details>`:''}</div></article>`;}
export function sourcesMarkup(library){
 const seen=new Set(),sources=library.sources.filter(s=>{if(seen.has(s.url))return false;seen.add(s.url);return true;});
 return `<section class="kl-bibliography" id="kg-bibliography"><header class="kl-section-heading"><div><p class="kg-kicker">THE EVIDENCE SHELF</p><h2>每一条知识，都有来处。</h2></div><p>${sources.length} 项课程、标准、指南与论文 · 核对 ${esc(library.checked)}</p></header><p class="kl-source-intro">正文为结合本站课程编写的学习解释，论文结果保留适用条件；影像注明出处。各节来源可直接打开原文，并标明已核对的范围。</p><details class="kl-all-sources"><summary>展开全部来源目录 <span>${sources.length} 项 ↗</span></summary><div class="kl-source-grid">${sources.map(s=>sourceCard(library,s)).join('')}</div></details></section>`;
}
